# Generated by Django 2.1 on 2018-08-21 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('type', models.CharField(choices=[('n', 'navigator'), ('sn', 'sub-navigator'), ('ne', 'neutral')], default='ne', max_length=2)),
                ('vertical_position', models.CharField(choices=[('t', 'top'), ('b', 'bottom'), ('ne', 'neutral')], default='ne', help_text='Choice the HTML vertical position of this menu if he is a navigator.', max_length=2)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('path', 'site')},
        ),
    ]
